In [1]:
import numpy as np

In [2]:
#Create a 1D NumPy array containing numbers from 0 to 9.
array = np.array([range(0,10)])

In [3]:
array

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [9]:
#Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.
array =np.array([3.14, 2.17, 0, 1, 2])

In [11]:
array = array.astype(int)
array

array([3, 2, 0, 1, 2])

In [13]:
#Create a 3x3 NumPy array with values ranging from 1 to 9.
arraynd = np.array([[1,2,3],[4,5,6],[7,8,9]])
arraynd

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
#Create a 2D NumPy array of shape (4, 5) filled with random numbers.
array = np.random.rand(4, 5)
array

array([[0.2940779 , 0.67855705, 0.47630918, 0.11689017, 0.61341779],
       [0.76652782, 0.80122814, 0.30144234, 0.49007345, 0.26975904],
       [0.1612404 , 0.00324754, 0.6080537 , 0.4780059 , 0.24648001],
       [0.69786444, 0.11627103, 0.41998176, 0.00434215, 0.99176953]])

In [21]:
array[1]

array([0.76652782, 0.80122814, 0.30144234, 0.49007345, 0.26975904])

In [28]:
#Reverse the order of elements in a given 1D NumPy array (first element becomes last)
original_array = np.array([0,1, 2, 3, 4, 5,6,7,8,9])

reversed_array = original_array[::-1]
reversed_array


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [29]:
#Create a 4x4 identity matrix using NumPy.
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
#Find the sum and average of a given 1D array
array = np.random.rand(4, 5)
print(array)
sum = np.sum(array)
avg = np.mean(array)
print("sum:", sum)
print("avg:", avg)

[[0.6346496  0.04506353 0.38809981 0.52808594 0.87149772]
 [0.80996219 0.82280439 0.84606042 0.66506066 0.21110122]
 [0.81173714 0.07787242 0.48829116 0.07642372 0.32168869]
 [0.80185772 0.23765786 0.49953007 0.27293906 0.1149016 ]]
sum: 9.5252849028503
avg: 0.47626424514251503


In [36]:
#Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.
array = np.array(range(1,21))
array.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [41]:
#Extract all odd numbers from a given NumPy array.
odd_array = array[array % 2 != 0]
odd_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])